name: sls
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.13
  url_launcher: ^6.0.0
  flutter_native_splash: ^2.3.10
  intl: ^0.17.0
  flare_flutter: ^3.0.2
  confetti: ^0.7.0
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6
  google_maps_flutter: ^2.1.0
  geolocator: ^7.6.2
  geocoding: ^2.0.1
  google_geocoding_api: ^1.4.1
  flutter_google_places: ^0.3.0

flutter_native_splash:
  color: "#FFFFFF" # Background color of the splash screen
  image: "assets/logo.png" # Path to your logo image
  android: true
  ios: true

  # Optional configurations for Android 12
  android_12:
    background_image: "assets/logo.png"
    image: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/title.jpeg
    - assets/lg_whitebg.png
    - assets/logo_blackbg.png
    - assets/lines.png
    - assets/people.png
    - assets/dress1.png
    - assets/dress2.png
    - assets/dress3.png
    - assets/dress4.png
    - assets/dress5.png
    - assets/r1.png
    - assets/sell.png
    - assets/buy.png

    
  fonts:
    - family: Gabriela-Regular
      fonts:
        - asset: fonts/Gabriela-Regular.ttf
